# kubectl apply -f hpa.yaml
# kubectl get hpa
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: php-apache-hpa
  targetCPUUtilizationPercentage: 20